### ISSUE TITLE
Determine List of Remaining Structural Changes Necessary

### ISSUE THREAD

**Issue by Flynnn** [psu-epl/psu-epl.github.com#36]
Determine List of Remaining Structural Changes Necessary

**Comment by Joedang** [comment]
I think most of the remaining stuff would be:   
- [ ] Add [little blurbs][printer index] to the different index pages that act as categories.
- [ ] Sort all the images to where they "ought" to be, wherever that is. I'm partial to each piece of equipment having its own `img` subdirectory, rather than having them all mushed into the main `images` directory. Though, a few things do belong in that top-level unsorted thing. 

I really wanted to add some kind of search functionality or a page that showed the site as a tree, but I don't think there's a reasonable way to do that.

For searching, you basically have to create a \[single\] file to search and provide some JavaScript that searches it. There are some open source solutions that... aren't very good. Google hosts a `search.js` that you can link to, but that solution offends me. The searchable file would basically be a big XML or JSON file that would include page titles (and keywords, if we started putting those in the headers). It could even include *the entire page contents*, but that's a little pants-on-head.

For a site tree, Jekyll/Liquid provides the paths to all the pages through the `site.pages` object. However, it's just a list of all the pages. It doesn't contain any parent/child structure. You could probably just write a tiny little Ruby function to do this and make it a Jekyll plugin... *But*, GH Pages only supports certain existing plugins for security reasons. You could probably do a bunch of logic with Liquid tags to cut apart the paths and group them into a directory structure, but that would be absolutely horrific. I'm also not sure if Liquid allows you to define functions, which you would need to be able to do in order to process an arbitrary number of nested directories.

So, I'd say a search and a site tree shouldn't be pursued until things are moved to the PSU site, since they'll be way easier there.

[printer index]: https://psu-epl.github.io/doc/equip/printer/

**Comment by jejor** [comment]
Any updates on this issue? @Flynnn @Joedang
